// Task ownership rules (BRB issue #3: "anyone can change anything they want").
//
// `tasks.edit` used to be tenant-wide: any holder could move or alter any task
// in the org. It now means "work on YOUR tasks" — the ones assigned to you or
// created by you. Cross-team reach is the separate `tasks.manage` permission
// (Admin, Demo Admin, Marketing Manager by default; editable on the roles
// matrix). Viewing is deliberately unchanged: the whole board stays visible so
// the team can still coordinate — only mutation is scoped.
//
// Pure functions, no I/O — the server actions and the pages both call these so
// the UI never offers a control the action would reject.

export type TaskActor = {
  id: string
  permissions: string[]
}

export type TaskOwnership = {
  createdById: string | null
  assignees: Array<{ userId: string }>
  // Legacy single-assignee column. Tasks generated by the handover chain (and
  // any row predating the multi-assignee migration) set this without writing a
  // task_assignees row, so it has to count as ownership too — otherwise the
  // delivery tasks the CRM creates for itself would belong to nobody.
  assigneeId?: string | null
}

/** Cross-team reach: every task in the tenant, regardless of who owns it. */
export function canManageAnyTask(actor: TaskActor): boolean {
  return actor.permissions.includes('tasks.manage')
}

/** Is this task the actor's own — assigned to them, or raised by them? */
export function ownsTask(actor: TaskActor, task: TaskOwnership): boolean {
  if (task.createdById === actor.id) return true
  if (task.assigneeId === actor.id) return true
  return task.assignees.some((a) => a.userId === actor.id)
}

/**
 * Work on a task: change its status, edit its fields, attach files.
 * Assumes `tasks.edit` was already required by the caller.
 */
export function canEditTask(actor: TaskActor, task: TaskOwnership): boolean {
  return canManageAnyTask(actor) || ownsTask(actor, task)
}

/**
 * Change WHO a task belongs to. Stricter than editing: an assignee may finish
 * their own work but may not hand it to someone else or take themselves off —
 * that stays with the creator and with tasks.manage holders.
 */
export function canReassignTask(actor: TaskActor, task: TaskOwnership): boolean {
  return canManageAnyTask(actor) || task.createdById === actor.id
}

export const TASK_EDIT_DENIED =
  'This task is not yours. Only its assignees, the person who created it, or someone with the "manage any task" permission can change it.'

export const TASK_REASSIGN_DENIED =
  'Only the person who created this task, or someone with the "manage any task" permission, can change who it is assigned to.'
