#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Zogency self-hosted installer (Ubuntu 22.04/24.04, Debian 12)
#
#   curl -fsSL https://raw.githubusercontent.com/steven-patrick18/Zogency/main/deploy/install.sh | sudo bash
#
# Prompts for: domain, agency name, admin email/password. Installs Docker if
# missing, generates secrets, builds and starts the stack with automatic HTTPS.
# Re-running is safe: it updates the code and restarts the stack.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="https://github.com/steven-patrick18/Zogency.git"
DIR="/opt/zogency"
BOLD='\033[1m'; GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'

say()  { echo -e "${GREEN}[zogency]${NC} $*"; }
fail() { echo -e "${RED}[zogency] $*${NC}" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || fail "Run with sudo: curl … | sudo bash"
command -v apt-get >/dev/null || fail "This installer supports Ubuntu/Debian (apt) only."

# ── Docker ──────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker…"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl git >/dev/null
  curl -fsSL https://get.docker.com | sh >/dev/null
fi
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin missing — install docker-compose-plugin and re-run."
command -v git >/dev/null || apt-get install -y -qq git >/dev/null

# ── Code ────────────────────────────────────────────────────────────────────
if [ -d "$DIR/.git" ]; then
  say "Updating existing install in $DIR…"
  git -C "$DIR" pull --ff-only
else
  say "Cloning Zogency into $DIR…"
  git clone --depth 1 "$REPO" "$DIR"
fi
cd "$DIR"

# ── Configuration (first run only) ──────────────────────────────────────────
ENV_FILE="$DIR/.env.production"
if [ ! -f "$ENV_FILE" ]; then
  # Prompts read from the terminal even when piped via curl | bash.
  exec < /dev/tty || true
  echo
  echo -e "${BOLD}Zogency setup — a few questions:${NC}"
  read -rp "  Domain (e.g. crm.youragency.com, DNS already pointed here): " DOMAIN
  [ -n "$DOMAIN" ] || fail "Domain is required."
  read -rp "  Agency name: " TENANT_NAME
  [ -n "$TENANT_NAME" ] || fail "Agency name is required."
  read -rp "  Admin email: " ADMIN_EMAIL
  [ -n "$ADMIN_EMAIL" ] || fail "Admin email is required."
  read -rsp "  Admin password (min 8 chars): " ADMIN_PASSWORD; echo
  [ "${#ADMIN_PASSWORD}" -ge 8 ] || fail "Password must be at least 8 characters."

  TENANT_SLUG=$(echo "$TENANT_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-\|-$//g' | cut -c1-30)
  say "Generating secrets…"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/install.sh $(date -u +%FT%TZ) — keep this file safe.
DOMAIN=${DOMAIN}
AUTH_URL=https://${DOMAIN}
AUTH_SECRET=$(openssl rand -base64 32 2>/dev/null || docker run --rm alpine/openssl rand -base64 32)
ZOGENCY_CREDENTIALS_KEY=$(openssl rand -base64 32 2>/dev/null || docker run --rm alpine/openssl rand -base64 32)
DB_PASSWORD=$(openssl rand -hex 24 2>/dev/null || docker run --rm alpine/openssl rand -hex 24)
SEED_TENANT_NAME=${TENANT_NAME}
SEED_TENANT_SLUG=${TENANT_SLUG}
SEED_ADMIN_NAME=Admin
SEED_ADMIN_EMAIL=${ADMIN_EMAIL}
SEED_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  chmod 600 "$ENV_FILE"
else
  say "Using existing $ENV_FILE"
fi

# ── Build & start ───────────────────────────────────────────────────────────
say "Building and starting the stack (first build takes a few minutes)…"
mkdir -p "$DIR/deploy/backups"
docker compose --env-file "$ENV_FILE" -f "$DIR/deploy/docker-compose.yml" up -d --build

DOMAIN_VALUE=$(grep '^DOMAIN=' "$ENV_FILE" | cut -d= -f2)
echo
say "──────────────────────────────────────────────────────────"
say "Zogency is starting at: ${BOLD}https://${DOMAIN_VALUE}${NC}"
say "  (HTTPS certificate is issued automatically on first visit"
say "   — make sure the DNS A-record points at this server)"
say ""
say "Next steps:"
say "  1. Log in with the admin email/password you just set"
say "  2. Settings → License → paste your Zogency license key"
say "     (the workspace is read-only until activated)"
say "  3. Settings → Integrations → connect your own accounts"
say ""
say "Update later:  curl -fsSL …/install.sh | sudo bash   (re-run = update)"
say "Logs:          docker compose -f $DIR/deploy/docker-compose.yml logs -f web"
say "Backups:       $DIR/deploy/backups (nightly, keep offsite copies!)"
say "──────────────────────────────────────────────────────────"
